---
deployment:
  tasks:
    - export DEPLOYPATH=/home/harpaljob/public_html
    # Clear the deployment directory first (excluding .htaccess)
    - /bin/find $DEPLOYPATH -mindepth 1 -not -name '.htaccess' -delete
    # Copy build files
    - /bin/cp -R build/* $DEPLOYPATH/
    # Copy .htaccess if it doesn't exist
    - /bin/cp -n .htaccess $DEPLOYPATH/
    # Set proper permissions
    - /bin/chmod 644 $DEPLOYPATH/.htaccess
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;