
import { Job } from "@/lib/types";

// Mock data for job listings
export const mockJobs: Job[] = [
  {
    id: "job-1",
    title: "Senior React Developer",
    company: "TechCorp",
    location: "San Francisco, CA",
    country: "United States",
    type: "full-time",
    salary: "$120,000 - $150,000",
    salaryMin: 120000,
    salaryMax: 150000,
    description: "We are looking for a senior React developer to join our team.",
    requirements: ["5+ years of experience with React", "TypeScript knowledge", "Team player"],
    responsibilities: ["Lead frontend development", "Code reviews", "Mentoring"],
    postedDate: "2023-11-15",
    logo: "/placeholder.svg",
    category: "Technology",
    featured: true,
    tags: ["React", "TypeScript", "Senior"],
    applicationDeadline: "2023-12-15",
    companyDescription: "Leading tech corporation",
    companySize: "50-200 employees",
    status: "active",
    views: 0,
    applications: 0,
    categoryId: "1",
    employerId: "1",
    companyId: "1",
    deadline: "2023-12-15",
    slug: "senior-react-developer",
    skills: ["React", "TypeScript", "JavaScript"],
    experience: "5+ years",
    benefits: ["Health insurance", "401k", "Remote work"],
    userId: "1"
  },
  {
    id: "job-2",
    title: "UX Designer",
    company: "DesignHub",
    location: "Remote",
    country: "United States",
    type: "full-time",
    salary: "$90,000 - $110,000",
    salaryMin: 90000,
    salaryMax: 110000,
    description: "Join our creative team as a UX Designer.",
    requirements: ["3+ years of UX design experience", "Portfolio", "Figma"],
    responsibilities: ["Create wireframes", "User research", "Prototyping"],
    postedDate: "2023-11-10",
    logo: "/placeholder.svg",
    category: "Design",
    companyDescription: "Creative design agency",
    companySize: "10-50 employees",
    status: "active",
    views: 0,
    applications: 0,
    categoryId: "2",
    employerId: "2",
    companyId: "2",
    deadline: "2023-12-10",
    slug: "ux-designer",
    skills: ["UX/UI", "Figma", "Design"],
    tags: ["UX/UI", "Figma", "Design"],
    experience: "3+ years",
    benefits: ["Flexible hours", "Design tools stipend"],
    featured: false,
    userId: "2"
  },
  {
    id: "job-3",
    title: "Marketing Manager",
    company: "GrowthCo",
    location: "New York, NY",
    country: "United States",
    type: "full-time",
    salary: "$85,000 - $100,000",
    salaryMin: 85000,
    salaryMax: 100000,
    description: "Lead our marketing efforts and drive growth.",
    requirements: ["5+ years in marketing", "B2B experience", "Analytics"],
    responsibilities: ["Campaign management", "Performance analysis", "Team leadership"],
    postedDate: "2023-11-05",
    logo: "/placeholder.svg",
    category: "Marketing",
    companyDescription: "Growth marketing agency",
    companySize: "20-100 employees",
    status: "closed",
    views: 0,
    applications: 0,
    categoryId: "3",
    employerId: "3",
    companyId: "3",
    deadline: "2023-12-05",
    slug: "marketing-manager",
    skills: ["Marketing", "Analytics", "Leadership"],
    tags: ["Marketing", "Analytics", "Leadership"],
    experience: "5+ years",
    benefits: ["Performance bonuses", "Hybrid work"],
    featured: false,
    userId: "3"
  },
  {
    id: "job-4",
    title: "Frontend Developer",
    company: "WebSolutions",
    location: "Austin, TX",
    country: "United States",
    type: "contract",
    salary: "$70 - $90 per hour",
    salaryMin: 70,
    salaryMax: 90,
    description: "We need a talented frontend developer for our client projects.",
    requirements: ["3+ years with JavaScript", "CSS expertise", "React knowledge"],
    responsibilities: ["Build responsive UIs", "Optimize performance", "Client communication"],
    postedDate: "2023-11-02",
    logo: "/placeholder.svg",
    category: "Technology",
    companyDescription: "Web development agency",
    companySize: "10-50 employees",
    status: "active",
    views: 0,
    applications: 0,
    categoryId: "1",
    employerId: "4",
    companyId: "4",
    deadline: "2023-12-02",
    slug: "frontend-developer",
    skills: ["JavaScript", "React", "CSS"],
    tags: ["JavaScript", "React", "CSS"],
    experience: "3+ years",
    benefits: ["Flexible schedule", "Project bonuses"],
    featured: false,
    userId: "4"
  },
  {
    id: "job-5",
    title: "Product Manager",
    company: "ProductFirst",
    location: "Seattle, WA",
    country: "United States",
    type: "full-time",
    salary: "$110,000 - $130,000",
    salaryMin: 110000,
    salaryMax: 130000,
    description: "Shape the future of our SaaS product.",
    requirements: ["4+ years in product management", "SaaS experience", "Technical background"],
    responsibilities: ["Roadmap planning", "Feature prioritization", "Cross-functional leadership"],
    postedDate: "2023-10-28",
    logo: "/placeholder.svg",
    category: "Technology",
    companyDescription: "SaaS product company",
    companySize: "50-200 employees",
    status: "draft",
    views: 0,
    applications: 0,
    categoryId: "1",
    employerId: "5",
    companyId: "5",
    deadline: "2023-11-28",
    slug: "product-manager",
    skills: ["Product Management", "SaaS", "Roadmap"],
    tags: ["Product Management", "SaaS", "Roadmap"],
    experience: "4+ years",
    benefits: ["Equity options", "Health benefits", "Flexible work"],
    featured: false,
    userId: "5"
  },
  {
    id: "job-6",
    title: "DevOps Engineer",
    company: "CloudTech",
    location: "Chicago, IL",
    country: "United States",
    type: "full-time",
    salary: "$130,000 - $160,000",
    salaryMin: 130000,
    salaryMax: 160000,
    description: "Join our infrastructure team to build and maintain cloud systems.",
    requirements: ["AWS/Azure experience", "CI/CD pipelines", "Kubernetes"],
    responsibilities: ["Cloud infrastructure", "Deployment automation", "Security"],
    postedDate: "2023-10-20",
    logo: "/placeholder.svg",
    category: "Technology",
    companyDescription: "Cloud solutions provider",
    companySize: "100-500 employees",
    status: "active",
    views: 0,
    applications: 0,
    categoryId: "1",
    employerId: "6",
    companyId: "6",
    deadline: "2023-11-20",
    slug: "devops-engineer",
    skills: ["AWS", "Docker", "Kubernetes"],
    tags: ["DevOps", "Cloud", "Infrastructure"],
    experience: "3-5 years",
    benefits: ["Remote work", "Learning budget", "Health insurance"],
    featured: true,
    userId: "6"
  }
];
